sudo: required
dist: trusty
addons:
    sonarcloud:
        organization: "opfab"
        token:
            secure: ${SONAR_TOKEN}
services:
  - docker
language: java
install: true
before_install:
  - sudo apt-get install realpath
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
script:
  - docker network create opfabnet
  - docker-compose -f src/main/docker/test-environment/docker-compose.yml up -d
  - ./gradlew copyDependencies build jacocoTestReport && sonar-scanner
deploy:
- provider: script
  skip_cleanup: true
  script: ./bin/travis/upload_doc.sh
  on:
    all_branches: true
    condition: $TRAVIS_EVENT_TYPE = cron



before_cache:
  # cleanup gradle caches
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  bundler: true
  directories:
    # caches gradle caches
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    # caches docker images
    - $HOME/docker