server:
  port: 2002
spring:
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://localhost:89
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/token(?<path>.*), /auth/realms/dev/protocol/openid-connect/token$\{path}
        - RewritePath=/auth/code/(?<params>.*), /auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client&$\{params}
        - RewritePath=/auth/check_token, /auth/realms/dev/protocol/openid-connect/token/introspect
        - AddRequestHeader=Authorization, Basic b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==
#        - RewritePath=/auth/(?<path>.*), /auth/oauth/$\{path}
#        - AddRequestHeader=Authorization, Basic Y2xpZW50SWRQYXNzd29yZDpzZWNyZXQ=
      - id: time
        uri: lb://TIME
        predicates:
        - Path=/time/**
        filters:
        - RewritePath=/time/(?<path>.*), /$\{path}
      - id: thirds
        uri: lb://THIRDS
        predicates:
        - Path=/thirds/**
        filters:
        - RewritePath=/thirds/(?<path>.*), /thirds/$\{path}
      - id: users
        uri: lb://USERS
        predicates:
        - Path=/users/**
        filters:
        - RewritePath=/users/(?<path>.*), /$\{path}
      - id: cards
        uri: lb://CARDS-CONSULTATION
        predicates:
        - Path=/cards/**
        filters:
        - RewritePath=/cards/(?<path>.*), /$\{path}
      - id: web-ui
        uri: lb://WEB-UI
        predicates:
        - Path=/ui/**
        filters:
        - RewritePath=/ui/(?<path>.*), /$\{path}
#      - id: config
#        uri: lb://CONFIG
#        predicates:
#        - Path=/config
#        filters:
#        - RewritePath=/config, /webui.json
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "Authorization, Content-Type"
#logging.level.root: debug