server:
  port: 2002
security:
  oauth2:
   client:
     clientId: clientIdPassword
     clientSecret: secret
     accessTokenUri: http://localhost:3000/auth/oauth/token
     userAuthorizationUri: http://localhost:3000/auth/oauth/authorize
   resource:
#     userInfoUri: http://localhost:3000/oauth/user/me
     jwt.key-value: 123
#     prefer-token-info: false
zuul:
  routes:
    token:
      path: '/auth/**'
      url: http://localhost:3000/auth/oauth/
      sensitiveHeaders: Cookie,Set-Cookie
