server:
  port: 2002
spring:
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://localhost:3000
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /auth/oauth/$\{path}
        - AddRequestHeader=Authorization, Basic Y2xpZW50SWRQYXNzd29yZDpzZWNyZXQ=
      - id: time
        uri: lb://TIME
        predicates:
        - Path=/time/**
        filters:
        - RewritePath=/time/(?<path>.*), /$\{path}
      - id: users
        uri: lb://USERS
        predicates:
        - Path=/users/**
        filters:
        - RewritePath=/users/(?<path>.*), /$\{path}
      - id: cards
        uri: lb://CARDS-CONSULTATION
        predicates:
        - Path=/cards/**
        filters:
#        - AddResponseHeader=Access-Control-Allow-Origin, *
#        - name: AddResponseHeader
#          args:
#            name: Allow
#            value: GET, HEAD, POST, PUT
        - RewritePath=/cards/(?<path>.*), /$\{path}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "authorization"
  level.root: debug