swagger: '2.0'
info:
  description: OperatorFabric ThirdParty Management API
  version: 0.1.1.SNAPSHOT
  title: Thirds Management
  termsOfService: ''
  contact:
    email: boris.dolley_AT_rte-france.com
    url: 'https://opfab.github.io/'
  license:
    name: Mozilla Public License V2.0
    url: 'http://mozilla.org/MPL/2.0/'
host: localhost
basePath: /apis
tags:
  - name: thirds
    description: Everything concerning specified Third
schemes:
  - http
paths:
  /thirds:
    get:
      tags:
        - thirds
      summary: List existing Thirds
      description: List existing Thirds
      operationId: getThirds
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Third'
  '/thirds/{thirdName}':
    get:
      tags:
        - thirds
      summary: Access existing Third data
      description: Access existing Third data
      operationId: getThird
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of template (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Third'
    post:
      tags:
        - thirds
      summary: Uploads Third configuration bundle
      description: >-
        Uploads Third configuration bundle. Bundle is a gzipped tarball (tar.gz)
        containing a config.json file and resource file using the following
        layout:

        ```

        └──css

        └──i18n

        │   └──en.json

        │   └──fr.json

        │   └...

        └──media

        │   └──sound1.wav

        │   └──sound2.ogg

        └──template

        │   └──en

        │   |  └──emergency.handlebars

        │   |  └──info.handlebars

        │   └──fr

        │   |  └──emergency.handlebars

        │   |  └──info.handlebars

        │   └...

        └──config.json

        ```

        The config.json file contains a Third object in json notation (see
        [Models](#__Models))
      operationId: uploadBundle
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to update
          required: true
          type: string
        - name: file
          in: formData
          description: file to upload
          required: true
          type: file
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Third'
  '/thirds/{thirdName}/templates/{templateName}':
    get:
      tags:
        - thirds
      summary: Get existing template associated with Third
      description: >-
        Get template associated with Third, if file exists return file
        (application/handlebars) otherwise return error message
        (application/json)
      operationId: getTemplate
      produces:
        - application/json
        - application/handlebars
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: false
          type: string
        - name: templateName
          in: path
          description: Name of template to retrieve (w.o. extension)
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of template (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
  '/thirds/{thirdName}/css/{cssFileName}':
    get:
      tags:
        - thirds
      summary: Get css file associated with Third
      description: >-
        Get css file associated with Third, if file exists return file
        (text/css) otherwise return error message (application/json)
      operationId: getCss
      produces:
        - application/json
        - text/css
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: cssFileName
          in: path
          description: Name of stylesheet file to retrieve (w.o. extension)
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of stylesheet (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
  '/thirds/{thirdName}/media/{mediaFileName}':
    get:
      tags:
        - thirds
      summary: Get media file associated with Third
      description: >-
        Get media file associated with Third, if file exists return file
        (audio/*) otherwise return error message (application/json)
      operationId: getMedia
      produces:
        - application/json
        - audio/*
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: mediaFileName
          in: path
          description: Name of media file to retrieve  (w.o. extension)
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: false
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of media (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
  '/thirds/{thirdName}/i18n':
    get:
      tags:
        - thirds
      summary: Get i18n file associated with Third
      description: >-
        Get i18n file associated with Third, if file exists return file
        (text/plain) otherwise return error message (application/json)
      operationId: getI18n
      produces:
        - application/json
        - text/plain
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of i18n (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
definitions:
  ThirdMenuEntry:
    type: object
    properties:
      id:
        type: string
        description: unique identifier of this menu item for the current third service
      url:
        type: string
        description: url of the endpoint for this menu item
      label:
        type: string
        description: >-
          i18n key for the label of this menu item.
          The value attached to this key should be defined in each XX.json file in the i18n folder of the bundle (where XX stands for the locale iso code, for example 'EN')
  Third:
    type: object
    description: >-
      Third party business module configuration. Models Third party properties
      and list referenced resources.
    properties:
      name:
        type: string
        description: Third party business module name
      version:
        type: string
        description: Third party business module configuration version
      templates:
        type: array
        description: List of templates name (without extension)
        example: '"emergency", "security"'
        items:
          type: string
      csses:
        type: array
        description: List of css file names (without extension)
        example: tab-style
        items:
          type: string
      i18nLabelKey:
        description: >-
          i18n key for the label of this Third
          The value attached to this key should be defined in each XX.json file in the i18n folder of the bundle (where XX stands for the locale iso code, for example 'EN')
        type: string
      medias:
        type: object
        description: List available medias
        additionalProperties:
          type: object
          properties:
            name:
              type: string
              description: media name
            files:
              type: array
              description: list of associated media files (with extension)
              example: jingle-bells.ogg
              items:
                type: string
      menuEntries:
        type: array
        description: describes the menu items to add to UI navbar
        items:
          $ref: '#/definitions/ThirdMenuEntry'
    required:
      - name
      - version
    example:
      name: My ThirdParty Application
      version: v1.0
      templates:
        - "emergency"
        - "info"
      csses:
        - "tab-style"
        - "content-style"
      i18nLabelKey: myThirdPartyApp.label
      medias:
        JingleBells:
          name: Jingle Bells
          files:
            - jingle-bells.ogg
            - vive-le-vent.ogg
        Alarm:
          name: Alarm sound
          files:
            - smallProblem.ogg
            - biggerProblem.ogg
            - abandonShip.ogg
      menuEntries:
        - id: website
          url: http://www.mythirdpartyapp.com
          label: menu.website
        - id: status
          url: http://www.mythirdpartyapp.com/status
          label: menu.status
